### ISSUE TITLE
Arma 3 Server       Next Time Update

### ISSUE THREAD

**Issue by ChrisHusky** [NovaRP/novamission.Altis#2]
09.03.2016
Next Time Update

 Polizei

- [ ]  Rangefinder zum Tempomessen
- [ ]  Polizeimeldung (ähnlich wie Adminmeldung)
- [ ]  Rucksäcke durchsuchen können
- [ ]  Dietriche im Cop shop oder mit Win- [ ]  Taste Fahrzeuge öffnen

- [ ]  Hundestaffel
	Lizens zum Hundeführer
	Hundestaffelshop
	Schäferhund (3D) Alsatian_Sand_F 	Alsatian_Black_F 	Alsatian_Sandblack_F
	benötigt zum suchen nach Drogen (Fahrzeuge/Personen nach Drogen durchsuchen)
	

- [ ]  Vernichtungsraum(- [ ]  box) 
	Init für Objete(Box) wo Items die darin liegen nach 10 Minuten entfernt werden

- [ ]  SEK Fahrzeugshop   (Hunter mit SEK Skin,Hunter HMG,UGV Stomper	[B_UGV_01_F])
- [ ]  SEK Helikoptershop (Ghosthawk)
- [ ]  SEK Bootshop (Gunboot)
	(alle aufgezählten Fahrzeuge,Helikopter und Bote aus den Shops für "normale" Polizisten entfernen

- [ ]  beim Durchsuchen von Personen werden Illegale Z- [ ]   und I- [ ]  Items/Sachen erkannt
- [ ]  Illegale I- [ ]  Items werden Nicht automatisch entfernt

- [ ]  Tigris zum "Wasserwerfer" nutzen (Taserwerfer?)

	Ausparkbar ab PD und SEK für Demos und Co.

	Funktionen: kann Taser abschießen mit voheriger Taser dauer ( 1,2,3,4,5 Minuten)
	Neuer Skin
	Lizens: Wasserwerfer Lizens (nicht kaufbare Lizens)

Steuerung

Shift + G ergeben

shift + R fesseln (Rebell mit Kabelbinder)

Windows- [ ]  Taste interaktion mit ergebenen und gefesselten Spielern (Ausrauben,mit Lizens + gefesselt Escortieren,mit Lizens +gefesselt Pullin)

ä Schranken öffnen (Cop)

o Warnmeldung der Polizei (cop,Achtung! Achtung! Hier spricht die Polizei, nehmmen Sie die Hände hoch! Sofort! [AJ einsprechen????])

ü Rangefinder zum Tempomessen (Rangefinder in der Handhalten und ü zum aktivieren/deaktivieren)

shift + L Blaulicht (Medic)

shift + F Sirene (Medic)

^ Spitzhacke nutzen

Animationen

shift + num1	Grüßen

shift + num2	Liegestütze

shift + num3	Kniebeuge

shift + num4	Kungfu

Millitärische Animationen

shift + num5	Vowärts	(Armbewegung nach vorne)	

shift + num6	Rückzug

shift + num7	Stop	(Geballtefaust)

- [ ]  neue Niederschlag Animation (nieder Boxen)

Script/Init

Schript  > Init
	wodurch ein objekt mit der Init ein I- [ ]   und Z- [ ]   inventar bekommt
	(in der init sollte man I und Z größe ändern können)

Logistik: Container und Fahrzeuge aufladen
	  Kleiner Container
	  Großer Container

Fahrzeuge: Offoader	 >Quad, kleinen Container
	  Zamak transport  > Quad,2 kleine Container, Limo,Limo(sport)
	  Zamak abgedeckt > Quad,2 kleine Container, Limo,Limo(sport)
	  Tempes transport  >Quad,3 kleine Container,1 großer Container,Limo,Limo(sport),SUV,Offroader,Truck,TruckBox,TruckFuel
	  Tempes abgedeckt  >Quad,3 kleine Container,1 großer Container,Limo,Limo(sport),SUV,Offroader
	  Hemmet transport  >Quad,3 kleine Container,1 großer Container,Limo,Limo(sport),SUV,Offroader,Truck,TruckBox,TruckFuel,Hunter,Ifrid,Offroader(Armed)
	  Hemmet abgedeckt >Quad,3 kleine Container,1 großer Container,Limo,Limo(sport),SUV,Offroader

- [ ]  erstellbarer Ausweiß  (Name,Vorname,Adresse)

- [ ]  Verletzte bewegen können (Win- [ ]  Taste)

- [ ]  im Cop Handy die Wanted+ um Anzeigen hinzuzufügen zu Spielern

- [ ]  Alarm bei abgebrochenen Dietrich,bei erfolgreichen kein Sound

- [ ]  Sound beim Fahrzeug aufschließen/abschließen

- [ ]  Bei Besitz eines GPS,ist die akktuelle Position auf der Map sichtbar

- [ ]  Recyclinghof sammeln von Items,siehe weiter unten

- [ ]  Handy kaufen um zu Telefonieren (funkgerät,kaufbar im Gerneralstore)
  
>	 Handy Akku der sich verbraucht

- [ ]  unsichtbaren UAA Rucksack (B_Carryall_ocamo)

- [ ]   Init für stühle zum rein setzen

- [ ]  Bei benutzen des Wasserspenders im Polizei HQ bekommt man free, eine Wasserflasche (als cop)

- [ ]  EMP Script für Hellcat

- [ ]  Beschlagnahmmte Fahrzeuge sind 1 Stunde nicht in der Garage

- [ ]  Gefesselten Personen den Mund zu "Tapen" (möglich als Cop und Civ,benötigt Klebeband)

- [ ]  leichen looten (I- [ ]   und Z- [ ]   Inventar)

- [ ]  Drogen benutzen/rauchen können (rausch bekommen, bei mehrfachen konsum stirbt man bzw. wird abhänig)

Lizenzen

Fessellizens			5 mio (permanent)
Escortlizens			5 mio (permanent)
Pulloutlizens			5 mio (permanent)
Logistiklizens		100k (permanent,aufladen von Fahrzeugen und Kisten)
Schwerlastlizens	150k (permanent,kaufen von Huron und Taru)

Kabelbinder		
GPS Tracker		
					
Klebeband(1x nutzbar)

Stoff		Baumwollplantage - [ ]  - [ ]  - [ ]  >	Weberrei - [ ]  - [ ]  - [ ]  > Stoffhändler/crafting
		Baumwolle 4 Platz	Stoff 2 Platz

Leder		Jagdgebiet - [ ]  - [ ]  - [ ]  >		Markt/crafting
		Leder 2 Platz

Anderes	

- [ ]  Z Items auf dem Boden mit Scrollen aufheben?? statt Win- [ ]  Taste + T

- [ ]  Spawnpunkt für Civis im Polizei HQ Kavala entfernen (Script seitig)

- [ ]  Fahrzeuge werden wieder automatisch nach dem Restart in die Garage gepackt

- [ ]  Kegel und Barrieren wieder in den Cop Item Shop packen

- [ ]  Markt in den Medicshop einfügen

- [ ]  Cops und Meics können am Markt auch einkaufen (bezogen auf Kavala,Pyrgos,... Markt)

- [ ]  Tankstellen Shop und ausraubbare Tankstellen akktivieren

Recyclinghof

Sammeln von Items durch Win- [ ]  Taste (Sammel Anitamtion,ca. 5 sec für´s Sammeln)

Recyclinghof Baupläne: bp_sting,bp_vermin
Items: Müll(1 platz),Plastik(),Leder(),Stoff(),Kabelbinder(),Eisenerz(),Kupfererz(),Apfel(),Wasserflasche(),Redgull(),Handy- [ ]  Akku(),

Gruppensystem

- [ ]  Gruppenbankkonto
	einzahlen von Geld auf das Gruppenkonto
	abhebbar nur vom Leader und CoLeader

- [ ]  Temporäre Ingamegruppen (1k zum gründen, nur bis Serverrestart da)
- [ ]  Permanente Ingamegruppen (werden durch Admins gemacht- [ ]  - [ ]  > Levelsystem)

- [ ]  Möglichkeit als Gruppierung in der Base/HQ zu spawnen 

Skins

neue Skins aus der Cloud einfügen

**Comment by Tobias0044** [comment]
-Tigris zum "Wasserwerfer" nutzen (Taserwerfer?)

Das müsste so sein wenn man getroffen wird als wenn man vom auto angefahren wurde und zuboden fällt.
